name: Test CLI with Pact Broker

on:
  workflow_dispatch:
  # push: # setup to run post release
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  cli:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, macos-14, windows-latest]
        shell: [bash]
        # include:
        #   - os: windows-latest
        #     shell: pwsh
        #   - os: windows-latest
        #     shell: cmd
      fail-fast: false
    steps:
    - uses: actions/checkout@v6 # required for local pact and test command script
    - uses: you54f/pact-broker-in-a-box@main
    - uses: pact-foundation/pact-cli@main
 
    - name: Show help commands
      run: |
        pact --help

    - name: Run pactbroker commands
      shell: bash
      run: ./run.sh
      env:
        PACT_BROKER_BASE_URL: http://localhost:9292
